//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEF6Tester.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_STUDENT
    {
        public decimal URID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> AGE { get; set; }
        public string REMARK1 { get; set; }
        public string REMARK2 { get; set; }
    }
}
